---
title: "153_project"
output: html_document
date: '2022-04-05'
---

```{r}
library(tidyverse)
library(ggplot2)
library(TSA)
```

# Original data
```{r}
phoenix=read.csv("phoenix_O3.csv")
plot(phoenix$O3.mean,type ="l")
```
# Smoothing only
```{r}
o3 = phoenix$O3.mean
smoothed= diff(o3)
plot(smoothed,type= "l")
acf(smoothed)
pacf(smoothed)
```
# Seasonal difference + Smoothing 
```{r}
# Check the periodogram
periodo = periodogram(o3,plot=TRUE,ylab="Periodogram", xlab="Frequency")

# Get the high magnitudes in descending order
order_spec = sort(periodo$spec,decreasing = TRUE)

# Get the frequency that gives max magnitude
first_max_index = which.max(periodo$spec)
first_maximizing_freq = periodo$freq[first_max_index]

# Get the frequency that gives second max magnitude
second_max = order_spec[2]
second_maximizing_freq = periodo$freq[periodo$spec==second_max]

t = 1:length(o3)
first_sin_max = sin(2*pi*first_maximizing_freq*t)
first_cos_max = cos(2*pi*first_maximizing_freq*t)
second_cos_max = cos(2*pi*second_maximizing_freq*t)
second_sin_max = cos(2*pi*second_maximizing_freq*t)

# Seasonal fitting
o3_sinusoid_freq_model = lm(o3 ~ t+ first_sin_max+first_cos_max+second_cos_max+second_sin_max)

# Get the residual, hoping for removing seasonality
seasonal_differenced =o3_sinusoid_freq_model$residuals

# with the seasonal differneced data, do the smoothing
smoooted_seasonal_differenced = diff(seasonal_differenced)

# plots
plot(smoooted_seasonal_differenced,type = "l")
acf(smoooted_seasonal_differenced)
pacf(smoooted_seasonal_differenced)
```


