---
title: "Non-parametric Model"
output: pdf_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)
library(astsa)
source('cleaning.R')
```

Deciding on signal model:

```{r}
# raw
ozone <- phoenix %>%
  pull(o3)
plot(ozone, type = 'l')
acf(ozone)

# yearly difference
d12 <- diff(ozone, lag = 12)
plot(d12, type = 'l')
acf2(d12)


# yearly difference + weekly difference
#d7d365 <- diff(diff(ozone, lag = 365), lag = 7)
#plot(d7d365, type = 'l')
#acf2(d7d365)


# yearly diff + weekly diff + first diff
#d1d7d365 <- diff(diff(diff(ozone, lag = 365), lag = 7))
#plot(d1d7d365, type = 'l')
#acf2(d1d7d365)

# this is the best candidate!
```

Pursuing stationarity:

```{r}
model1 <- sarima(ozone, p = 0, d = 0, q = 0, P = 1, D = 1, Q = 1, S = 12)
model1$AIC
model1$AICc
model1$BIC

model2 <- sarima(ozone, p = 0, d = 0, q = 0, P = 0, D = 1, Q = 1, S = 12)
model2$AIC
model2$AICc
model2$BIC


# first SARIMA that passes Ljung-Box test!!
#sarima(d365, p = 3, d = 1, q = 1, P = 1, D = 1, Q = 1, S = 7)


# final models
#model1 <- sarima(d365, p = 3, d = 0, q = 1, P = 1, D = 0, Q = 2, S = 7)
#model1$AIC
#model1$AICc
#model1$BIC

#model2 <- sarima(d365, p = 3, d = 0, q = 1, P = 1, D = 0, Q = 1, S = 7)
#model2$AIC
#model2$AICc
#model2$BIC

# auto.arima(d365) suggested model
#mtest <- auto.arima(d365, max.order = 7, stepwise = FALSE, approximation = FALSE, d = 0, D = 0)

#acf2(d365)
#sarima(d365, p = 3, d = 0, q = 1)


# others
#sarima(d365, p = 3, d = 0, q = 1, P = 1, D = 1, Q = 1, S = 7)
```

Cross-validation:

```{r}
sse <- matrix(NA, nrow = 2, ncol = 6)  # Jan 2010 to Dec 2010

# train on 2004-2009, test on 2010-2015
for (i in 1:6) {
  train <- ozone[1:(12 * (i + 5))]
  test <- ozone[(12 * (i + 5) + 1):(12 * (i + 6))]
  
  m1 <- sarima.for(train, n.ahead = 12,  # 30
                   p = 0, d = 0, q = 0, P = 1, D = 1, Q = 1, S = 12)
  m2 <- sarima.for(train, n.ahead = length(test),
                   p = 0, d = 0, q = 0, P = 0, D = 1, Q = 1, S = 12)
  
  sse[1,i] <- sum((test - m1$pred)^2)
  sse[2,i] <- sum((test - m2$pred)^2)
}

rowSums(sse, na.rm = TRUE)
```


look at acf of residuals and qq plot as well as box test
x_t raw, v_t diff, v_t is the sarima
auto.arima search parameters, eg. order




