---
title: "Signal Model 2"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)
library(astsa)
source('cleaning.R')
```

Deciding on signal model:

```{r}
# raw
ozone <- phoenix$o3
plot(ozone, type = 'l')

# yearly difference
d365 <- diff(ozone, lag = 365)
plot(d365, type = 'l')

# yearly difference + order 1 difference
d1d365 <- diff(d365)
plot(d1d365[1:1000], type = 'l')

# yearly difference + order 2 difference
d1d1d365 <- diff(d1d365)
plot(d1d1d365[1:1000], type = 'l')

acf2(d1d1d365)

# yearly difference + order 1 difference + weekly difference
d7d1d365 <- diff(d1d365, lag = 7)
plot(d7d1d365[1:1000], type = 'l')

acf2(d7d1d365)

# yearly difference + weekly difference
d7d365 <- diff(d365, lag = 7)
plot(d7d365[1:1000], type = 'l')

acf2(d7d365)

# yearly difference + order 2 difference + weekly difference
d7d1d1d365 <- diff(d7d1d365)
plot(d7d1d1d365[1:1000], type = 'l')

acf2(d7d1d1d365)

# yearly diff + order 2 weekly diff + order 1 diff
d1d7d7d365 <- diff(diff(diff(diff(ozone, lag = 365), lag = 7), lag = 7))
plot(d1d7d7d365, type = 'l')

acf2(d1d7d7d365)

```

Pursuing stationarity:

```{r}



auto.arima(d7d1d1d365)
sarima(d7d1d1d365, p = 1, d = 2, q = 1, Q = 1, S = 7)




# current test
acf2(d7d1d365)
sarima(d365, p = 3, d = 1, q = 1, D = 1, Q = 1, S = 7)





acf2(d7d1d365)
auto.arima(d7d1d365)
sarima(d7d1d365, p = 0, d = 0, q = 1)



sarima(d1d365, p = 1, d = 0, q = 2)

```












